site_name: The TrackingDb API Example

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep orange
    accent: deep orange
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: deep orange
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"

extra_css:
  - 'extra/terminal.css'
  - 'extra/tweaks.css'
extra_javascript:
  - 'extra/feedback.js'
  - 'extra/fluff.js'
  - 'https://samuelcolvin.github.io/mkdocs-run-code/run_code_main.js'

markdown_extensions:
- tables
- def_list
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            extensions:
              - docs/plugins/griffe_doclinks.py
          import:
            - https://docs.python.org/3/objects.inv

nav:
- Home: index.md
- Techniques in the example:
  - Used design patterns: abstractions.md
  - Tests using MonkeyPatch: test_monkey_patch.md
  - Separate test data files: test_data_files.md
  - Database integrity: db_integrity.md
  - Using bulk Upsert: bulk_upserts.md
  - Splitting big batches into smaller sub-batches: bulk_upsert_split.md
  - OpenAPI documentation: openapi_docs.md
- Code documentation:
  - Main modules:
      - main: source/main.md
      - run: source/run.md
      - insert_bigger_batch: source/insert_batch.md
  - core:
    - database: source/core_db.md
    - documentation: source/core_docs.md
    - models: source/core_models.md
    - unified_logging: source/core_logging.md
  - API modules:
    - sms_document:
      - documentation: source/sms_document_docs.md
      - models: source/sms_document_models.md
      - sms_document_crud: source/sms_document_crud.md
      - sms_document_routes: source/sms_document_routes.md
      - unit_of_work: source/sms_document_uow.md
    - sms_transfer:
      - documentation: source/sms_transfer_docs.md
      - models: source/sms_transfer_models.md
      - sms_transfer_crud: source/sms_transfer_crud.md
      - sms_transfer_routes: source/sms_transfer_routes.md
      - unit_of_work: source/sms_transfer_uow.md
  - tests:
      - pytest.ini: pytest_ini.md
      - conftest: source/conftest.md
      - test_sms_document_crud: source/test_sms_doc_crud.md
      - test_sms_document_route: source/test_sms_doc_route.md
      - test_sms_transfers_crud: source/test_sms_tran_crud.md
      - test_sms_transfers_route: source/test_sms_tran_route.md
      - test_validation_model: source/test_validation_model.md
